language: python

cache:
    - pip
    - npm

node_js:
    - "5.11.1"
python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    - sudo pip install vim-vint
    - bash test/install.sh

script:
    - bash test/test.sh
